### ISSUE TITLE
Add Lock in Landscape

### ISSUE THREAD

**Issue by suhail-mir** [spotxmobile/spotx-demo-android#10]
Hi, I am working on a video app where video player is locked in landscape mode, even is device orientation is set to potrait mode. When the add is played either pre roll or midroll ads, they are played in potrait mode. I would like to lock ads as well in landscape mode. How can we do that, because i am not able to find any config setting to do so.

**Comment by scottjulian** [comment]
There is no config for setting the orientation as it is orientation agnostic. You must set up your UIView to the size and orientation you wish and will the ad will size itself appropriately. The ad view is able to start in landscape or portrait; And it responds to orientation changes as well. You simply have to configure your app settings and UIView correctly. 

Without seeing your integration code, I have no way of knowing if you're correctly configuring your app.
