### ISSUE TITLE
Sample App is not working

### ISSUE THREAD

**Issue by dkk009** [spotxmobile/spotx-demo-android#6]
Hi, I downloaded spotX library. For me sample app is not working, even documentation also missing. Could you help me to figure out, how i can integrate SpotX Interstitial ad in my Android App.

**Comment by lcniles** [comment]
We'd be glad to help. Can you tell me which version of Android Studio you are using?

**Comment by dkk009** [comment]
Android Studio-2.1.2, In sample project many resources are missing, Because of that , I couldn't able to build it.

**Comment by lcniles** [comment]
My apologies, it looks like there are some unwanted files in there leftover from a merge commit. I removed them.

**Comment by dkk009** [comment]
Thanks lcniles, Now i able build the sample app.
