### ISSUE TITLE
Spotx BackPressed

### ISSUE THREAD

**Issue by Sanket990** [spotxmobile/spotx-demo-android#8]
#I have integrated SPOTX sample and working perfect. But how to handle **OnBackPressed() event** when Video Ad loaded (Video Start and Video end  between).

**Comment by scottjulian** [comment]
Can you provide more information? Are you experiencing an issue?

**Comment by Sanket990** [comment]
In Android Device- Spotx Video Start and End second between "back pressed" not handle


    @Override
    public void onBackPressed() {
 super.onBackPressed();  //Finish Video-Ad not working
    }

**Comment by scottjulian** [comment]
When is `onBackPressed()` not handled? During the playback of the ad, we launch a new activity, where SpotX overrides the `onBackPressed()` event so users cannot skip the Ad. After the Ad has finished playing, we cleanup the activity and return to the previous one.
